In [26]:
import numpy as np 
import pandas as pd 
import plotly.express as px

In [27]:
df=pd.read_csv("house-prices - house-prices.csv")

In [28]:
df.head()

,area,price
0,1567,177067.50
1,3345,511748.20
2,3722,404096.67
3,2783,357916.31
4,2949,362409.54


In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   area    1000 non-null   int64  
 1   price   1000 non-null   float64
dtypes: float64(1), int64(1)
memory usage: 15.8 KB


In [30]:
df.shape

(1000, 2)

In [31]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
area,1000.0,2972.92000,1128.465907,1002.00,2063.5000,2918.50,3917.75,5000.00
price,1000.0,348132.02097,142136.964031,-19630.31,249198.3075,348351.02,449603.30,734120.22


In [32]:
df.isna().sum()

area     0
price    0
dtype: int64

In [33]:
df.duplicated().sum()

0

### Ordinary Least Square (OLS)

In [34]:
x_bar=df.area.mean()
x_bar

2972.92

In [35]:
y_bar=df.price.mean()
y_bar

348132.02097

In [36]:
theta_1 = sum( (df.area - x_bar) * (df.price - y_bar) ) / sum((df.area - x_bar) ** 2)
theta_0 = y_bar - (theta_1 * x_bar)

print(theta_0)
print(theta_1)

60953.77652271936
96.59803978824881


In [37]:
from sklearn.linear_model import LinearRegression

LinearRegressionModel = LinearRegression()

LinearRegressionModel.fit(df[['area']], df['price'])

LinearRegression()

In [38]:
print("coefficient is : " ,LinearRegressionModel.coef_)
print("intercept is :" ,LinearRegressionModel.intercept_)

coefficient is :  [96.59803979]
intercept is : 60953.776522719534


In [39]:
LinearRegressionModel.predict([[1700]])

C:\Users\Sigma\AppData\Roaming\Python\Python311\site-packages\sklearn\utils\validation.py:2739: UserWarning:

X does not have valid feature names, but LinearRegression was fitted with feature names



array([225170.44416274])

In [40]:
px.scatter(data_frame= df, x= 'area', y= 'price', trendline= 'ols', trendline_color_override= 'red')

In [41]:
area_predicted = LinearRegressionModel.predict(df[['area']])
area_predicted

array([212322.90487091, 384074.21961441, 420491.68061458, 329786.12125342,
       345821.39585827, 405712.18052698, 266417.80715232, 360600.89594587,
       484342.98491461, 276657.19936988, 509651.67133913, 204208.66952869,
       234540.4540222 , 453721.40630174, 447249.33763593, 343503.04290335,
       179479.5713429 , 197253.61066394, 329592.92517384, 334519.42520304,
       178996.58114396, 325052.81730379, 462222.0338031 , 158421.19866906,
       331138.49381045, 504435.37719057, 201020.93421568, 198316.18910161,
       442419.43564651, 287959.1700251 , 454977.18081899, 259655.94436715,
       351520.68020577, 277816.37584734, 225073.84612295, 344179.22918186,
       527232.5145806 , 162091.92418102, 176485.03210947, 259752.54240694,
       432663.0336279 , 489849.07318254, 193293.09103262, 259559.34632736,
       440101.0826916 , 170302.75756302, 212999.09114942, 286123.80726913,
       322251.47414993, 510231.25957786, 187497.20864533, 175422.45367179,
       315296.41528518, 4

In [42]:
df['price_predicted']=area_predicted
df['price_predicted']

0      212322.904871
1      384074.219614
2      420491.680615
3      329786.121253
4      345821.395858
           ...      
995    393444.229474
996    208748.777399
997    264002.856158
998    210777.336234
999    470915.857384
Name: price_predicted, Length: 1000, dtype: float64

In [43]:
df.head()

,area,price,price_predicted
0,1567,177067.50,212322.904871
1,3345,511748.20,384074.219614
2,3722,404096.67,420491.680615
3,2783,357916.31,329786.121253
4,2949,362409.54,345821.395858


### Gradient Descent

In [44]:
from sklearn.linear_model import SGDRegressor

sgd = SGDRegressor()

sgd.fit(df[['area']], df['price'])

SGDRegressor()

In [45]:
sgd.eta0

0.01

In [46]:
sgd.early_stopping

False

In [47]:
price_predicted_sgd = sgd.predict(df[['area']])
price_predicted_sgd

array([-3.27988144e+15, -7.00140210e+15, -7.79049844e+15, -5.82508342e+15,
       -6.17253698e+15, -7.47025510e+15, -4.45201393e+15, -6.49278032e+15,
       -9.17403340e+15, -4.67388187e+15, -9.72242396e+15, -3.10406157e+15,
       -3.76129300e+15, -8.51052269e+15, -8.37028541e+15, -6.12230273e+15,
       -2.56822957e+15, -2.95335882e+15, -5.82089723e+15, -5.92764502e+15,
       -2.55776410e+15, -5.72252183e+15, -8.69471493e+15, -2.11193513e+15,
       -5.85438673e+15, -9.60939690e+15, -3.03498947e+15, -2.97638285e+15,
       -8.26563072e+15, -4.91877383e+15, -8.53773290e+15, -4.30549737e+15,
       -6.29602951e+15, -4.69899899e+15, -3.55616981e+15, -6.13695439e+15,
       -1.01033670e+16, -2.19147270e+15, -2.50334366e+15, -4.30759046e+15,
       -8.05422825e+15, -9.29333974e+15, -2.86754197e+15, -4.30340428e+15,
       -8.21539647e+15, -2.36938566e+15, -3.29453310e+15, -4.87900505e+15,
       -5.66182211e+15, -9.73498252e+15, -2.74195635e+15, -2.48031963e+15,
       -5.51111936e+15, -

In [48]:
df['price_predicted_sgd'] = price_predicted_sgd

In [49]:
df

,area,price,price_predicted,price_predicted_sgd
0,1567,177067.50,212322.904871,-3.279881e+15
1,3345,511748.20,384074.219614,-7.001402e+15
2,3722,404096.67,420491.680615,-7.790498e+15
3,2783,357916.31,329786.121253,-5.825083e+15
4,2949,362409.54,345821.395858,-6.172537e+15
...,...,...,...,...
995,3442,434336.51,393444.229474,-7.204432e+15
996,1530,211400.14,208748.777399,-3.202437e+15
997,2102,172513.03,264002.856158,-4.399687e+15
998,1551,200701.84,210777.336234,-3.246392e+15


In [51]:
fig = px.scatter(df, x='area', y='price')
fig.add_scatter(x=df['area'], y=df['price_predicted_sgd'], 
                mode='lines', line=dict(color='red'), 
                name='price_predicted_sgd').show()